# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Robotshell
tagline:          ''
description:      'Cybersecurity Auditor & Penetration Tester, Cybersecurity Professor and Bug Bounty Researcher'

author:
  name:           'Robotshell'
  url:            https://twitter.com/robotshelld

paginate:         5

# Custom vars
github:
  repo:           https://github.com/poole/robotshell
