# Site settings
title: robotshell
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Robotshell
user_description: Hello, world! My name is Robotshell, and I am a passionate hacker with several years of experience in the field. I work as a Cybersecurity Auditor & Penetration Tester, and I am also a specialist teacher in Cybersecurity. I have had the opportunity to share my knowledge through cybersecurity conferences. I am actively involved in the hacking community, contributing through reporting CVEs, exploits, creating tools, and many other activities. I also participate in Bug Bounty programs, where I find vulnerabilities and help secure various platforms. Feel free to explore my projects and connect with me. Happy hacking!
email: robotshelld@protonmail.com
twitter_username: robotshelld
github_username:  robotshell

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
