# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Robotshell
tagline:          ''
description:      'Cybersecurity Auditor & Penetration Tester, Cybersecurity Professor and Bug Bounty Researcher'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Robotshell'
  url:            https://twitter.com/robotshelld

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/robotshell
