# Site settings
title: robotshell
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Robotshell
user_description: Hello, world! My name is Robotshell, and I am a passionate hacker with several years of experience in the field. Constantly striving to learn and improve, I dedicate myself to continuous education and exploration of new technologies. As a Bug Bounty researcher, I enjoy finding vulnerabilities and helping to secure various platforms. Feel free to explore my projects and connect with me. Happy hacking!
user_title: Cybersecurity Auditor & Penetration Tester
email: robotshelld@protonmail.com
twitter_username: robotshelld
github_username:  robotshell

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
